this is a practice notebook you run whatever you want to test here quickly if needed

In [7]:
import plotly.express as px
data_canada = px.data.gapminder().query("country == 'Canada'")
fig = px.bar(data_canada, x='year', y='pop')
fig.show()
data_canada

    country continent  year  lifeExp       pop    gdpPercap iso_alpha  iso_num
240  Canada  Americas  1952   68.750  14785584  11367.16112       CAN      124
241  Canada  Americas  1957   69.960  17010154  12489.95006       CAN      124
242  Canada  Americas  1962   71.300  18985849  13462.48555       CAN      124
243  Canada  Americas  1967   72.130  20819767  16076.58803       CAN      124
244  Canada  Americas  1972   72.880  22284500  18970.57086       CAN      124
245  Canada  Americas  1977   74.210  23796400  22090.88306       CAN      124
246  Canada  Americas  1982   75.760  25201900  22898.79214       CAN      124
247  Canada  Americas  1987   76.860  26549700  26626.51503       CAN      124
248  Canada  Americas  1992   77.950  28523502  26342.88426       CAN      124
249  Canada  Americas  1997   78.610  30305843  28954.92589       CAN      124
250  Canada  Americas  2002   79.770  31902268  33328.96507       CAN      124
251  Canada  Americas  2007   80.653  33390141  36319.23501       CAN      124

In [8]:
import plotly.express as px

long_df = px.data.medals_long()

fig = px.bar(long_df, x="nation", y="count", color="medal", title="Long-Form Input")
fig.show()
long_df

        nation   medal  count
0  South Korea    gold     24
1        China    gold     10
2       Canada    gold      9
3  South Korea  silver     13
4        China  silver     15
5       Canada  silver     12
6  South Korea  bronze     11
7        China  bronze      8
8       Canada  bronze     12

In [11]:
import plotly.express as px

df = px.data.gapminder()
df_2007 = df.query("year==2007")

for template in ["plotly", "plotly_white", "plotly_dark", "ggplot2", "seaborn", "simple_white", "none"]:
    fig = px.scatter(df_2007,
                     x="gdpPercap", y="lifeExp", size="pop", color="continent",
                     log_x=True, size_max=60,
                     template=template, title="Gapminder 2007: '%s' theme" % template)
    fig.show()